FROM python:3.6-slim
USER root
WORKDIR /
RUN mkdir /python-scripts
WORKDIR /python-scripts
ADD ./start.py /python-scripts
COPY ./scripts /python-scripts
RUN chmod -R 777 ./ && \
    python -m pip install pymongo && \
    python -m pip install googlemaps && \
    python -m pip install python-telegram-bot && \
    python -m pip install urlopen
CMD [ "python", "/python-scripts/start.py" ]
